server:
  port: 8077

spring:
  application:
    name: OSS_SERVICE
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: "4096MB"
      maxRequestSize: "4096MB"
  mvc:
    favicon:
      enabled: false
  task:
    execution:
      thread-name-prefix: task-pool-
      pool:
        core-size: 4
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: scheduling-
      pool:
        size: 2

logging:
  level:
    ROOT: INFO
    com.berry.oss: DEBUG