server:
  port: 8077
  undertow:
    buffer-size: 1024
    direct-buffers: true
    io-threads: 4
    worker-threads: 32

spring:
  application:
    name: oss-service
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: "1024MB"
      maxRequestSize: "1024MB"
  mvc:
    favicon:
      enabled: false
  jackson:
    # 输出为指定格式字符串
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  task:
    execution:
      thread-name-prefix: task-pool-
      pool:
        core-size: 4
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: scheduling-
      pool:
        size: 2

logging:
  level:
    ROOT: INFO
    com.berry.oss: DEBUG
